server:
  port: 2222
eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://${eureka.instance.hostname}:1111/eureka/
spring:
  application:
    name: ribbon-product